### ISSUE TITLE
Unable to execute !

### ISSUE THREAD

**Issue by netslutter** [metamorphose/metamorphose2#31]
Traceback (most recent call last):
File "/usr/share/metamorphose2/metamorphose2.py", line 36, in <module>
import app
File "/usr/share/metamorphose2/app.py", line 56, in <module>
realPath = __set_real_path()
File "/usr/share/metamorphose2/app.py", line 48, in __set_real_path
path = path.decode(sys.getfilesystemencoding())
AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

**Comment by timinaust** [comment]
Hi, not sure but it looks like an issue between python 2 and python 3. Which branch/fork of metamorphose, python and wxpython are you running? The version here only works with python 2, not python 3.  There are a couple of versions for python 3 on various forks.
